function Hd = FIR_BLW_05_Hz
%FIR_BLW_05_HZ Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.11 and DSP System Toolbox 9.13.
% Generated on: 23-Dec-2021 22:19:54

% Equiripple Highpass filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 300;  % Sampling Frequency

Fstop = 0.5;             % Stopband Frequency
Fpass = 1;               % Passband Frequency
Dstop = 0.0001;          % Stopband Attenuation
Dpass = 0.057501127785;  % Passband Ripple
dens  = 16;              % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fstop, Fpass]/(Fs/2), [0 1], [Dstop, Dpass]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
