function Hd = NOtch_50
%NOTCH_50 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.11 and DSP System Toolbox 9.13.
% Generated on: 23-Dec-2021 21:32:17

% IIR Notching filter designed using the IIRNOTCH function.

% All frequency values are in Hz.
Fs = 300;  % Sampling Frequency

Fnotch = 50;  % Notch Frequency
BW     = 1;   % Bandwidth
Apass  = 1;   % Bandwidth Attenuation

[b, a] = iirnotch(Fnotch/(Fs/2), BW/(Fs/2), Apass);
Hd     = dfilt.df2(b, a);

% [EOF]
